export interface VimExercise {
  id: number
  title: string
  titleTr: string
  description: string
  descriptionTr: string
  initialContent: string
  goalContent: string
  hint: string
  hintTr: string
  expectedMotion: string
  category: string
}

export const exercises: VimExercise[] = [
  // Basic motions
  {
    id: 1,
    title: 'Delete a word',
    titleTr: 'Bir kelime sil',
    description: 'Delete the word "bad" using dw. Place your cursor on "bad" first.',
    descriptionTr: 'dw kullanarak "bad" kelimesini silin. İmlecinizi önce "bad" üzerine yerleştirin.',
    initialContent: 'This is a bad example of text.',
    goalContent: 'This is a example of text.',
    hint: 'Move to "bad" with w, then press dw',
    hintTr: 'w ile "bad"e gidin, sonra dw basın',
    expectedMotion: 'dw',
    category: 'Motions',
  },
  {
    id: 2,
    title: 'Delete a line',
    titleTr: 'Bir satır sil',
    description: 'Delete the second line using dd.',
    descriptionTr: 'dd kullanarak ikinci satırı silin.',
    initialContent: 'Keep this line.\nDelete this line.\nKeep this too.',
    goalContent: 'Keep this line.\nKeep this too.',
    hint: 'Move to line 2 with j, then press dd',
    hintTr: 'j ile 2. satıra gidin, sonra dd basın',
    expectedMotion: 'dd',
    category: 'Motions',
  },
  {
    id: 3,
    title: 'Change inner word',
    titleTr: 'İç kelimeyi değiştir',
    description: 'Change "hello" to "world" using ciw.',
    descriptionTr: 'ciw kullanarak "hello"yu "world" olarak değiştirin.',
    initialContent: 'Say hello to everyone.',
    goalContent: 'Say world to everyone.',
    hint: 'Navigate to "hello", press ciw, type "world", press Esc',
    hintTr: '"hello"ya gidin, ciw basın, "world" yazın, Esc basın',
    expectedMotion: 'ciw',
    category: 'Text Objects',
  },
  {
    id: 4,
    title: 'Change inside quotes',
    titleTr: 'Tırnak içini değiştir',
    description: 'Change the text inside quotes from "old" to "new".',
    descriptionTr: 'Tırnak içindeki metni "old"dan "new"a değiştirin.',
    initialContent: 'const name = "old"',
    goalContent: 'const name = "new"',
    hint: 'Place cursor inside quotes, press ci", type "new"',
    hintTr: 'İmleci tırnakların içine koyun, ci" basın, "new" yazın',
    expectedMotion: 'ci"',
    category: 'Text Objects',
  },
  {
    id: 5,
    title: 'Delete to end of line',
    titleTr: 'Satır sonuna kadar sil',
    description: 'Delete everything from "remove" to end of line using D.',
    descriptionTr: 'D kullanarak "remove"dan satır sonuna kadar silin.',
    initialContent: 'Keep this remove everything here',
    goalContent: 'Keep this ',
    hint: 'Move to "remove" with w/f, then press D',
    hintTr: 'w/f ile "remove"a gidin, sonra D basın',
    expectedMotion: 'D',
    category: 'Operators',
  },
  {
    id: 6,
    title: 'Yank and paste a line',
    titleTr: 'Satırı kopyala ve yapıştır',
    description: 'Duplicate the first line below itself using yy and p.',
    descriptionTr: 'yy ve p kullanarak ilk satırı altına kopyalayın.',
    initialContent: 'Duplicate me.\nI stay here.',
    goalContent: 'Duplicate me.\nDuplicate me.\nI stay here.',
    hint: 'Press yy to yank, then p to paste below',
    hintTr: 'yy ile kopyalayın, sonra p ile altına yapıştırın',
    expectedMotion: 'yy p',
    category: 'Operators',
  },
  {
    id: 7,
    title: 'Change inside parentheses',
    titleTr: 'Parantez içini değiştir',
    description: 'Change the function argument from "x" to "y".',
    descriptionTr: 'Fonksiyon argümanını "x"ten "y"ye değiştirin.',
    initialContent: 'console.log(x)',
    goalContent: 'console.log(y)',
    hint: 'Place cursor inside parens, press ci), type "y"',
    hintTr: 'İmleci parantez içine koyun, ci) basın, "y" yazın',
    expectedMotion: 'ci)',
    category: 'Text Objects',
  },
  {
    id: 8,
    title: 'Go to line and delete',
    titleTr: 'Satıra git ve sil',
    description: 'Delete line 3.',
    descriptionTr: '3. satırı silin.',
    initialContent: 'Line one\nLine two\nLine three\nLine four',
    goalContent: 'Line one\nLine two\nLine four',
    hint: 'Press 3G to go to line 3, then dd',
    hintTr: '3G ile 3. satıra gidin, sonra dd basın',
    expectedMotion: '3G dd',
    category: 'Motions',
  },
  {
    id: 9,
    title: 'Replace character',
    titleTr: 'Karakter değiştir',
    description: 'Change "cat" to "bat" by replacing "c" with "b".',
    descriptionTr: '"c"yi "b" ile değiştirerek "cat"i "bat" yapın.',
    initialContent: 'The cat sat on the mat.',
    goalContent: 'The bat sat on the mat.',
    hint: 'Move to "c" in cat, press rb',
    hintTr: 'cat\'teki "c"ye gidin, rb basın',
    expectedMotion: 'r',
    category: 'Operators',
  },
  {
    id: 10,
    title: 'Join lines',
    titleTr: 'Satırları birleştir',
    description: 'Join these two lines into one using J.',
    descriptionTr: 'J kullanarak bu iki satırı birleştirin.',
    initialContent: 'Hello\nWorld',
    goalContent: 'Hello World',
    hint: 'Press J to join current line with next',
    hintTr: 'J basarak mevcut satırı sonrakiyle birleştirin',
    expectedMotion: 'J',
    category: 'Operators',
  },
  {
    id: 11,
    title: 'Indent a block',
    titleTr: 'Bloğu girintile',
    description: 'Indent lines 2-3 to the right.',
    descriptionTr: '2-3. satırları sağa girintileyin.',
    initialContent: 'function hello() {\nconsole.log("hi")\nreturn true\n}',
    goalContent: 'function hello() {\n  console.log("hi")\n  return true\n}',
    hint: 'Go to line 2, press V to enter visual line, j to select, then >',
    hintTr: '2. satıra gidin, V ile görsel satır moduna girin, j ile seçin, sonra >',
    expectedMotion: 'V j >',
    category: 'Visual Mode',
  },
  {
    id: 12,
    title: 'Delete inside braces',
    titleTr: 'Süslü parantez içini sil',
    description: 'Delete everything inside the curly braces.',
    descriptionTr: 'Süslü parantezlerin içindeki her şeyi silin.',
    initialContent: 'const obj = { key: "value", other: 123 }',
    goalContent: 'const obj = {}',
    hint: 'Place cursor inside braces, press di}',
    hintTr: 'İmleci süslü parantez içine koyun, di} basın',
    expectedMotion: 'di}',
    category: 'Text Objects',
  },
  {
    id: 13,
    title: 'Search and jump',
    titleTr: 'Ara ve atla',
    description: 'Find the word "target" using /target.',
    descriptionTr: '/target kullanarak "target" kelimesini bulun.',
    initialContent: 'Some text here and more text.\nAnother line with target word.\nLast line.',
    goalContent: 'Some text here and more text.\nAnother line with target word.\nLast line.',
    hint: 'Type /target then Enter',
    hintTr: '/target yazın sonra Enter',
    expectedMotion: '/target',
    category: 'Search/Replace',
  },
  {
    id: 14,
    title: 'Global replace',
    titleTr: 'Toplu değiştir',
    description: 'Replace all "foo" with "bar" in the file.',
    descriptionTr: 'Dosyadaki tüm "foo"ları "bar" ile değiştirin.',
    initialContent: 'foo is foo and foo again',
    goalContent: 'bar is bar and bar again',
    hint: 'Type :%s/foo/bar/g',
    hintTr: ':%s/foo/bar/g yazın',
    expectedMotion: ':%s/foo/bar/g',
    category: 'Search/Replace',
  },
  {
    id: 15,
    title: 'Visual block edit',
    titleTr: 'Görsel blok düzenleme',
    description: 'Add "//" comment at the start of all 3 lines.',
    descriptionTr: 'Tüm 3 satırın başına "//" yorum ekleyin.',
    initialContent: 'line one\nline two\nline three',
    goalContent: '//line one\n//line two\n//line three',
    hint: 'Ctrl+v, 2j, I, type "//" , Esc',
    hintTr: 'Ctrl+v, 2j, I, "//" yazın, Esc',
    expectedMotion: 'Ctrl+v I',
    category: 'Visual Mode',
  },
  {
    id: 16,
    title: 'Delete a paragraph',
    titleTr: 'Paragraf sil',
    description: 'Delete the entire middle paragraph.',
    descriptionTr: 'Ortadaki paragrafın tamamını silin.',
    initialContent: 'First paragraph here.\n\nMiddle paragraph to delete.\nWith two lines.\n\nLast paragraph stays.',
    goalContent: 'First paragraph here.\n\n\nLast paragraph stays.',
    hint: 'Move to middle paragraph, press dip',
    hintTr: 'Orta paragrafa gidin, dip basın',
    expectedMotion: 'dip',
    category: 'Text Objects',
  },
  {
    id: 17,
    title: 'Swap two lines',
    titleTr: 'İki satırı değiştir',
    description: 'Swap line 1 and line 2.',
    descriptionTr: '1. ve 2. satırı değiştirin.',
    initialContent: 'Second line\nFirst line\nThird line',
    goalContent: 'First line\nSecond line\nThird line',
    hint: 'Press ddp to move current line down, or dd then k then P',
    hintTr: 'ddp ile mevcut satırı aşağı taşıyın',
    expectedMotion: 'ddp',
    category: 'Operators',
  },
  {
    id: 18,
    title: 'Use f and ; to navigate',
    titleTr: 'f ve ; ile gezin',
    description: 'Delete the third comma in the line.',
    descriptionTr: 'Satırdaki üçüncü virgülü silin.',
    initialContent: 'a, b, c, d, e',
    goalContent: 'a, b, c d, e',
    hint: 'f, ;; to reach 3rd comma, then x',
    hintTr: 'f, ;; ile 3. virgüle ulaşın, sonra x',
    expectedMotion: 'f, ;; x',
    category: 'Motions',
  },
  {
    id: 19,
    title: 'Change a tag content',
    titleTr: 'Tag içeriğini değiştir',
    description: 'Change "old text" inside the <p> tag to "new text".',
    descriptionTr: '<p> tag içindeki "old text"i "new text" olarak değiştirin.',
    initialContent: '<p>old text</p>',
    goalContent: '<p>new text</p>',
    hint: 'Place cursor inside tag, press cit, type "new text"',
    hintTr: 'İmleci tag içine koyun, cit basın, "new text" yazın',
    expectedMotion: 'cit',
    category: 'Text Objects',
  },
  {
    id: 20,
    title: 'Record and play macro',
    titleTr: 'Makro kaydet ve çalıştır',
    description: 'Add semicolons to the end of each line. Record a macro on line 1, replay on others.',
    descriptionTr: 'Her satırın sonuna noktalı virgül ekleyin. 1. satırda makro kaydedin, diğerlerinde çalıştırın.',
    initialContent: 'const a = 1\nconst b = 2\nconst c = 3\nconst d = 4',
    goalContent: 'const a = 1;\nconst b = 2;\nconst c = 3;\nconst d = 4;',
    hint: 'qa A; Esc j q then 3@a',
    hintTr: 'qa A; Esc j q sonra 3@a',
    expectedMotion: 'qa A; Esc j q @a',
    category: 'Macros',
  },
]
