name = "aburakt-api"
main = "src/index.ts"
compatibility_date = "2025-03-01"

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "aburakt-db"
database_id = "d79a8e9c-ad38-4461-b15b-e4ee280fba62"
migrations_dir = "migrations"

# Secrets (set via `wrangler secret put`):
# GITHUB_CLIENT_ID
# GITHUB_CLIENT_SECRET
# SESSION_SECRET
